// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw01mqnG73u79UDkA4amftSU0mI6_gUM8',
    appId: '1:151034945518:web:73598e1144de56671fb8ff',
    messagingSenderId: '151034945518',
    projectId: 'classnotes-f2b8d',
    authDomain: 'classnotes-f2b8d.firebaseapp.com',
    storageBucket: 'classnotes-f2b8d.firebasestorage.app',
    measurementId: 'G-QYQKMS00X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH9sRvQMgZLueaUNhi4ymMdJ1Um4YJ_KI',
    appId: '1:151034945518:android:68d5edaff124cf261fb8ff',
    messagingSenderId: '151034945518',
    projectId: 'classnotes-f2b8d',
    storageBucket: 'classnotes-f2b8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCER4opyUUmTk6XWpJH1pmhy3sI0rrUP0I',
    appId: '1:151034945518:ios:123b6b427e97bd331fb8ff',
    messagingSenderId: '151034945518',
    projectId: 'classnotes-f2b8d',
    storageBucket: 'classnotes-f2b8d.firebasestorage.app',
    iosBundleId: 'tz.co.nyumbaplus.classnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCER4opyUUmTk6XWpJH1pmhy3sI0rrUP0I',
    appId: '1:151034945518:ios:123b6b427e97bd331fb8ff',
    messagingSenderId: '151034945518',
    projectId: 'classnotes-f2b8d',
    storageBucket: 'classnotes-f2b8d.firebasestorage.app',
    iosBundleId: 'tz.co.nyumbaplus.classnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw01mqnG73u79UDkA4amftSU0mI6_gUM8',
    appId: '1:151034945518:web:45f00974040c02911fb8ff',
    messagingSenderId: '151034945518',
    projectId: 'classnotes-f2b8d',
    authDomain: 'classnotes-f2b8d.firebaseapp.com',
    storageBucket: 'classnotes-f2b8d.firebasestorage.app',
    measurementId: 'G-KQCG59K9F2',
  );
}
